---
- name: Komplettes System-Update auf dem ThinkPad
  hosts: notebooks
  become: true

  tasks:
    - name: Fedora DNF-Pakete aktualisieren
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true

    - name: Systemweite Flatpak-Pakete aktualisieren
      ansible.builtin.command: flatpak update -y --system
      changed_when: false

    - name: User Flatpak-Pakete aktualisieren
      ansible.builtin.command: flatpak update -y --user
      become: false
      changed_when: false

